In [36]:
print ('Hello word') # avá

Hello word


In [37]:
conta = 7+11 # avá

In [38]:
print ('7' ' + ' '11' ' = ' , conta) # virgula, funciona para separar 'string' com 'int'.


7 + 11 =  18


In [43]:
nome = 'André'
idade = '27' 
peso = '85.4'   


In [44]:
print (nome, idade, peso)

André 27 85.4


In [ ]:
nome = input ('Digite seu nome:') # input, é usado para colocar um nome como se dosse o 'sout 

In [ ]:
print (nome)

Gustavo


In [2]:
idade = input ('digite sua idade: ')

In [3]:
print (idade)

85


In [2]:
lanche = ('☕','🥛','🍞','🍰')

In [3]:
print(lanche[3]) #sempre começa de 0 então o pão ficaria  ☕ = 0 ,🥛 = 1,🍞 = 2,🍰 = 3

🍰


In [4]:
lanche[3]= '🍮' # o erro aqui , é por que não se poe alterar, POR SE TRATAR DE UMA TUPLA.

TypeError: 'tuple' object does not support item assignment

In [5]:
print(lanche) #sem alteração

('☕', '🥛', '🍞', '🍰')


In [6]:
lanche = ['☕','🥛','🍞','🍰'] #vamos tentar alterear quando se trata de uma lista.

In [7]:
lanche[3]= '🍮' #aqui vai substituir a posição 3 por 🍮

In [8]:
print(lanche)# aqui trocamos, por se tratar de LISTAS, listas podem ser alteradas no decorrer do código.

['☕', '🥛', '🍞', '🍮']


In [9]:
lanche.append('🍪')# adicionamos como o apendice, mais uma coisa na nossa lista, nem preciso flar que se fosse tuples nao daria né?

In [10]:
print(lanche)

['☕', '🥛', '🍞', '🍮', '🍪']


In [11]:
lanche.remove('🍞') # removemos um elmento.

In [12]:
print(lanche) #easey pesy

['☕', '🥛', '🍮', '🍪']


In [13]:
if '🍪' in lanche:
    lanche.remove("🍪")
# se um elemento estiver dentro de lanche, remova-o.

In [14]:
print(lanche)

['☕', '🥛', '🍮']


In [22]:
import numpy as np

In [25]:
jogos = [5 , 6, 7]

In [26]:
np.array(jogos)

array([5, 6, 7])

In [27]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.linspace(1,3,6)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])